### ISSUE TITLE
Update Development Version Installation Instructions For Spyder 4 As Default

### ISSUE THREAD

**Issue by qrqiuren** [spyder-ide/spyder-docs#102]
## Issue Description

Because Spyder 4 is the default version in the repository, some instructions that distinct version 3 and 4 are no longer necessary.

### Where is the relevant portion of the documentation located?

In doc/installation.rst there is a long note about how to install development environment for spyder 4:

```rst
#. Install the Spyder `requirements`_.

   The recommended and easiest way to do this is with ``conda`` (although experts may prefer ``pip``). In a fresh environment (``conda create -n your-name-here -c conda-forge python=3``, then ``activate`` it), run the following:

   .. code-block:: bash

      conda install -c conda-forge/label/beta spyder=4.0.0b1
      conda install -c conda-forge python-language-server
      conda remove spyder

   This installs all of Spyder's dependencies into the environment along with the stable/packaged version of Spyder, and then removes Spyder itself.

   .. note::

      Following the separation in v3.3 of Spyder's console code into its own package, ``spyder-kernels``, you'll need to have the corresponding version of it available—``0.x`` for Spyder 3 (``3.x`` branch), and ``1.x`` for Spyder 4 (``master`` branch).
      The above procedure will install the ``0.x`` version; to test the ``master`` branch (Spyder 4), you'll need to install the corresponding ``1.x`` version of ``spyder-kernels``.
      This can be done via two methods: installing the ``1.x`` version via ``conda``:

      .. code-block:: bash

         conda install -c spyder-ide spyder-kernels=1.*

      or ``pip``:

      .. code-block:: bash

         pip install spyder-kernels==1.*

      (and using the same respective command, replacing ``1`` with ``0``, to switch back to the Spyder 3 version), or by ``clone``-ing the `spyder-kernels git repository`_ to somewhere on your path and checking out the appropriate branch (``0.x`` or ``master``) corresponding to the version of Spyder (3 or 4) you would like to run, and running the commend ``pip install -e`` at the root.
      For any non-trivial development work, keeping two separate virtual environments (with ``conda-env`` or ``venv``) for Spyder 3 and 4 makes this process much quicker and less tedious.
```

### What would you suggest it be replaced with?

Delete these notes and fix the commands to proper ones.

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

* Are you planning on submitting a Github pull request with a suitable change?
Yes.

* Anything else you'd like to add?

**Comment by CAM-Gerlach** [comment]
@qrqiuren Thanks for your contribution. The issue is that the docs are nowhere near ready for Spyder 4 yet; they need a comprehensive update which we recently got a grant for and @juanis2112 will be working with help from myself and @ccordoba12 . As part of that, this will be updated; these docs aren't actually live on our production site and presumably won't be until the aforementioned project is at least far enough along. Also, a lot of content in this note is still valid and should simply be reworded, not thrown out entirely as this proposes, which I also discuss on your PR.

@juanis2112 @ccordoba12 Thoughts?
