### ISSUE TITLE
Add FAQ on how to do complex regex searches with the Find panel

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-docs#107]
See https://github.com/spyder-ide/spyder/issues/11368

**Comment by CAM-Gerlach** [comment]
I would advise just including a small section in the Editor docs discussing the various features of the Find and Replace panel, and referring the user to one or a few guides covering how to use basic regex and maybe an interactive regex tester like regexr; there's no need to duplicate effort given its just standard regex on which innumerabe guides exist online. @juanis2112 would you want to add this to the docs as part of your work?

**Comment by juanis2112** [comment]
Adding this in Find pane features docs

**Comment by CAM-Gerlach** [comment]
This could be included to the to-be-added section in the Editor docs about the Find panel, though probably in a later PR since its an advanced feature and not really anything specific to Spyder—we could probably just mention it and link to an existing regex tutorial instead of re-inventing the wheel here.

**Comment by hyounes4560** [comment]
@CAM-Gerlach Could you please add more info about this?

**Comment by CAM-Gerlach** [comment]
Sorry for the confusion. I don't think we need a whole FAQ as the initial issue proposed; just a simple link to a regex resource, e.g. the Python `re` docs ([like we do for the `Find` pane](https://docs.spyder-ide.org/current/panes/findinfiles.html#choosing-search-options)), will suffice where you already mention this option, IMO. The Find pane docs discusses the Find pane, while the find and replace panel is part of the Editor (though they both have several similar options, including regex and case-sensitive toggles). I'll propose a suggestion over there.
