### ISSUE TITLE
Implement a modern Sphinx html theme that matches our website

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs#11]
## Issue Description

Right now, our current theme is very dated and quite horribly at odds with that of our website, so it needs to be updated. Therefore, we wanted to solicit everyone's feedback as part of that process. So...

@spyder-ide/core-developers @spyder-ide/junior-developers 

While I have a specific proposal as a starting point, its ultimately up to the consensus on what we go with, built-in or third party, so long as it is straightforward to install and use the theme, and it is under an appropriate license. Let's hear your feedback and/or suggestions!

### My Proposal

As a starting point, I took the built-in [Alabaster](https://alabaster.readthedocs.io/en/latest/) sphinx theme and heavily customized it with the supported options to fit our needs, which you can view as PR #12  . Out of the [built in sphinx themes](http://www.sphinx-doc.org/en/stable/theming.html), I found it to match the look and feel of our website the best (particularly once the font was changed to the same one the latter uses), and it is also one of if not the most modern, well-supported, and customizable, with many extra and advanced features most of its counterparts lacked. 

This allowed me to match the font (Open Sans) and exact color palette (same light and dark grey colors, and a hint of the same out of the tube red as the accent color) as the logo and website, and also allowed for adding a github watch/star widget and fork banner, and a dynamic Travis build status widget like our doc has, as well as extra links to all of major web properties (which could also be used in the future to easily host a link to an alternate (Spyder 3/4) edition of the docs if/when we start deploying those.

In any case, aside from the above, it is undeniably convenient, reliable and future proof to use a core built-in theme rather relying on something third-party. However, if there is a substantially better third party option available that is straightforward to get working reliably, then we can certainly use that instead. Therefore, I welcome your feedback on this baseline, and look forward to your further suggestions. Thanks!

![image](https://user-images.githubusercontent.com/17051931/38169398-d9c1bcf0-352e-11e8-9e19-6add161167b4.png)

![image](https://user-images.githubusercontent.com/17051931/38169410-3c223e74-352f-11e8-9e7a-a2a0ceee37a9.png)

![image](https://user-images.githubusercontent.com/17051931/38169394-b91ed2f8-352e-11e8-91c9-add236544a7f.png)

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Why didn't #12 automatically close this like it said it would?

**Comment by ccordoba12** [comment]
Probably because `Fixes` was not in the first comment.

**Comment by CAM-Gerlach** [comment]
@ccordoba12  Huh; I had this from the beginning...

![image](https://user-images.githubusercontent.com/17051931/38846072-04f5bcf8-41c0-11e8-8046-f187ccb73d96.png)
