### ISSUE TITLE
Update "Installing a development build" about git-subrepo

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-docs#110]
I think the section [Installing a development build](https://docs.spyder-ide.org/installation.html#installing-a-development-build) needs to be updated now that we use `git subrepo` for `spyder-kernels`.

I was actually looking for the instructions about `git subrepo`, but could not find them easily.

**Comment by ccordoba12** [comment]
> I was actually looking for the instructions about git subrepo, but could not find them easily.

They are in the [Contributing guide](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md) of the Spyder repo. Only people that needs to do joint PRs to Spyder and spyder-kernels need to know about them, so that's why I didn't consider necessary to add them to our docs.

**Comment by jitseniesen** [comment]
Fair enough, and I see now that there is a link to the Contributing guide in that section
