### ISSUE TITLE
Add a development subdomain for latest (develop) docs

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-docs#113]
Add a new subdomain for having the latest development docs deployed

**Comment by CAM-Gerlach** [comment]
The simplest way to do it, without creating another repo, seperate keys, or even a subdomain is to just deploy it to `develop` (or similar) subdir of the existing GH pages site, which Doctr should be able to easily do with just a couple extra lines in the `.travis.yml`. If you agree I can go ahead right now; the code I need to add should just be

```bash
- if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
    doctr deploy dev --built-docs doc/_build/html";
  else
    doctr deploy . --built-docs doc/_build/html --branch-whitelist 3.x;
  fi
```

In fact, we can use this to deploy multiple versions of the docs simultaneously (e.g. 3.x, 4.x, 5.x) by simply changing the last line to ``doctr deploy "$TRAVIS_BRANCH" --built-docs doc/_build/html --branch-whitelist 3.x 4.x 5.x;``, though I'd need to add some kind of UI to the theme to switch between them, or find a better theme (like RTD) that supports that automagically.

**Comment by ccordoba12** [comment]
@CAM-Gerlach, your solution is way simpler than we had planned with @goanpeca! Could you open a PR for it?

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I was initially thinking of the same thing as @goanpeca but reading the doctr docs, this approach is far simpler to implement and scales with additional branches as required.

**Comment by CAM-Gerlach** [comment]
@goanpeca agrees so its decided then. I'll create a PR in a little bit, and you can suggest whatever name you want for the subpath there if you want something longer than `dev`.

**Comment by goanpeca** [comment]
Thanks! indeed it is a much simpler solution :-) 👍
