### ISSUE TITLE
Remove dependencies information from docs

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder-docs#123]
## Issue Description

Information of dependencies is not necessary anymore because they are mentioned in dependencies.py plus as they change frequently it makes it harder to update in the docs

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

* Are you planning on submitting a Github pull request with a suitable change?

* Anything else you'd like to add?

**Comment by CAM-Gerlach** [comment]
@juanis2112 It would be likely be easiest for me to do this along with my other updates to the install guide.

**Comment by juanis2112** [comment]
okay go ahead. Thanks!

**Comment by CAM-Gerlach** [comment]
Sure thing, thanks!
