### ISSUE TITLE
Use git subrepo to have the theme inside the repo

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder-docs#133]
## Issue Description

Use git subrepo to manage the theme installation

**Comment by CAM-Gerlach** [comment]
What's the thinking on Git subrepo vs. normal Git submodules? I understand the latter introduces an extra dep, but are the advantages worth it?

**Comment by dalthviz** [comment]
I guess it simplifies the number of commands to update the subrepo/submodule. Maybe @ccordoba12 has more info about it.

**Comment by ccordoba12** [comment]
Yes, regular users doesn't need to understand nor having anything to do with git subrepos. Besides, it's quiet easy to manage a subrepo per branch, whereas I don't think that's possible with submodules.

**Comment by CAM-Gerlach** [comment]
Okay, sounds good. Just make sure its documented in the Contributing guide for the non-normal contributors; I've used submodules a lot but not subrepos yet.

**Comment by CAM-Gerlach** [comment]
Given this issue has gone stale, the theme has been relatively stable with few coupled changes (or major changes of any kind), this was not a major obstacle in practice once everything was in production, and there doesn't appear to be a clear need for adding extra complexities and dependencies in the docs build process, I think we can safety close this.
