### ISSUE TITLE
Make the navbar look as it does in the current stable theme

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#144]
This is how the navbar looks in the stable version of our docs:

![Selección_028](https://user-images.githubusercontent.com/365293/89065731-d8a87b80-d331-11ea-824d-7d8c0482c8fe.png)

And this is how it looks in the development one:

![Selección_029](https://user-images.githubusercontent.com/365293/89065771-e9f18800-d331-11ea-9004-91e16b609c09.png)

I think we need to make them match so the navbar looks the same as the one in our main website too.

Also, the `Home` link in the development navbar is not pointing to `www.spyder-ide.org`

**Comment by ccordoba12** [comment]
@dalthviz, please take care of this one.

**Comment by dalthviz** [comment]
Being worked on spyder-ide/spyder-docs-sphinx-theme/pull/12
