### ISSUE TITLE
Icons in cards lost their blue color

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#152]
We noticed this in our meeting with Isabella yesterday. I think it's a regression introduced by PR #148.

@CAM-Gerlach, could you take a look at this one? Thanks!

**Comment by CAM-Gerlach** [comment]
Again? :facepalm: I'll take a look...it didn't happen when I tested that PR locally, so I'm not sure what caused it, but I indeed see its missing on the site.

**Comment by CAM-Gerlach** [comment]
Somehow a one-character typo crept in there...oops.

**Comment by ccordoba12** [comment]
Thanks @CAM-Gerlach for the fast response!
