### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by rgommers** [spyder-ide/spyder-docs#159]
I got here because I was searching for the latest version of the docs with the new Sphinx theme. I didn't manage to find them, and in addition I noticed that the `Building and deploying` section of the README still talks about "Spyder 4 in Q1 2019 if we get funding". Can this be updated?

**Comment by ccordoba12** [comment]
Thanks Ralf for the feedback. I'll do it.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I can take care of it now
