### ISSUE TITLE
Add link to index page in the sidebar

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder-docs#164]
## Issue Description
I think it would be useful to add a "Home" item in the sidebar pointing the index page as the only "HOME" button that is currently in the page points to the Spyder's main page and it is not quite clear that to go to the index page of the docs they should click the Spyder's DOCS element in the nav bar.

![Screen Shot 2020-08-06 at 4 46 11 PM](https://user-images.githubusercontent.com/18587879/89585925-58d45280-d804-11ea-8734-120a6947513b.png)

I suggest having home on top of the installation guide. (Not sure if we should call it home or something else)

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

* Are you planning on submitting a Github pull request with a suitable change?

* Anything else you'd like to add?

**Comment by ccordoba12** [comment]
> I suggest having home on top of the installation guide. (Not sure if we should call it home or something else)

Agreed on the location and also on calling it "Home".

**Comment by ccordoba12** [comment]
Sorry, we shouldn't call it "Home" because there's another "Home" on the navbar, and having two of them would be really confusing.

So my suggestions are "Main page" or "Landing page".

**Comment by juanis2112** [comment]
Maybe we can rename the current overview to something like "Quick Start" and have the Overview point to index.

**Comment by ccordoba12** [comment]
Very good idea too @juanis2112!

**Comment by CAM-Gerlach** [comment]
> Maybe we can rename the current overview to something like "Quick Start" and have the Overview point to index.

Great idea @juanis2112; that would be my preference.
