### ISSUE TITLE
Image centering sometimes looks off

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder-docs#170]
## Issue Description

The images don't look centered since the text is left aligned as discussed with @ccordoba12 

### Where is the relevant portion of the documentation located?

Images in the docs
![image](https://user-images.githubusercontent.com/16781833/90174643-eca99f80-dd6b-11ea-9686-980e445a8958.png)

### What would you suggest it be replaced with?

Check a way to improve the centering of the images (maybe adding some negative margin to the right of paragraphs to enable them covert more width even if they are left-aligned).

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

* Are you planning on submitting a Github pull request with a suitable change?

* Anything else you'd like to add?

**Comment by CAM-Gerlach** [comment]
So, what's the plan on this one @juanis2112 ? Close it as wontfix, add some sort of padding adjustment, use left-aligned images, something else?
