### ISSUE TITLE
Set up UI, redirects and deployment for use with multiple versions of the docs

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs#179]
## Issue Description

As part of #162 , we need to implement version switching in the docs. What we want is:

* [ ] Each set of docs (3.x, 4.x, and eventually 5.x) deployed to a subdirectory corresponding to the version number (which is trivial for me to do with what I've already set up with doctor)
* [ ] A dropdown menu at the top of the page to select the version of the current page of the docs to show, like the Python.org docs have (I imagine that's pretty doable for you on the theme level, e.g. in the page template generate the dropdown menu items/links using the page URL + a list of versions/subdomains in the conf.py)
* [ ] Redirects from the base doc URLs (with no version number in the URL path) to whatever version is the current stable, also like the Python.org docs do (which I'm really not sure is possible given its a static site on a host we don't control). If this isn't possible, I guess what we could do is simply have our CI script deploy whatever version is the current stable twice, once to the subdirectory and once to the root (assuming that doctr doesn't delete files and directories that don't match what's in the deploy; if it does, we could either do some hackery or just deploy the stable version to e.g. `stable`, create some kind of landing page and have to update all our links one more time (i.e. what I did in #39 )

@dalthviz says: 

Maybe is worthy to create [an issue] in the docs repo and add there any resource or new info that could help us to implement this

Checking I found [this extension](https://holzhaus.github.io/sphinx-multiversion/master/index.html
) that generates/handles the different version of docs taking into account branches/tags.

**Comment by dalthviz** [comment]
Note: Possible extension to do the redirects - https://github.com/sphinx-contrib/redirects

**Comment by CAM-Gerlach** [comment]
Sorry, thought I replied to this before. I'm not sure how sphinx-redirect will work at least with sphinx-multiversion, since it only redirects things relative to the Sphinx source dir, not the actual deployed dir, so I'm not sure how it would work between deployed branches. Also, if we used it, we'd have to still write code to manually build a list of all the docs to actually make the manual redirects, so unless another tool exists (which I haven't found) we will either need to write our own to do it after the build runs, or just have only the root path redirect and update any external links to point to a stable tag (which we could include a few git commands in our Travis build script to automatically create and point to the tip of the latest stable branch, so we don't have to update it manually with every PR).

 Thoughts?

**Comment by CAM-Gerlach** [comment]
Sure, sounds fine to me.

Do note that what we do about the redirects will inherently depend on the build process changes with `sphinx-multiversion`, so I can't actually do much until that's implemented. However, what I propose to do is the following, after sphinx-multiversion builds the docs and before doctr deploys them to Github pages:

1. Copy the HTML build output of the current stable branch ( for now, `4.x`) to a `stable` subdirectory (simple cp command)
2. Run a Python script to recursively generate redirect pages (of the form suggested by Sphinx-Multiversion) to every HTML page in the `stable` dir, and outputs them to equivalent paths in the root dir (so that docs.spyder-ide.org/editor.html would redirect to docs.spyder-ide.org/4.x/editor.html  

We could skip step 1 and redirect everything directly to the current stable version number directory, but that would mean URLs copied from the addressbar would link directly to a specific version, which the vast majority of the time is not is what is actually desirable in the long term as these would get stale and point to out of date versions, and if people actually select a version from the dropdown, they will get the version-specific URLs they deliberately selected.

**Comment by CAM-Gerlach** [comment]
_Realized I never posted this, including for postarity_

Sure, sounds fine to me.

Do note that what we do about the redirects will inherently depend on the build process changes with `sphinx-multiversion`, so I can't actually do much until that's implemented. However, what I propose to do is the following, after sphinx-multiversion builds the docs and before doctr deploys them to Github pages:

1. Copy the HTML build output of the current stable branch ( for now, `4.x`) to a `stable` subdirectory (simple cp command)
2. Run a Python script to recursively generate redirect pages (of the form suggested by Sphinx-Multiversion) to every HTML page in the `stable` dir, and outputs them to equivalent paths in the root dir (so that docs.spyder-ide.org/editor.html would redirect to docs.spyder-ide.org/4.x/editor.html  

We could skip step 1 and redirect everything directly to the current stable version number directory, but that would mean URLs copied from the addressbar would link directly to a specific version, which the vast majority of the time is not is what is actually desirable in the long term as these would get stale and point to out of date versions, and if people actually select a version from the dropdown, they will get the version-specific URLs they deliberately selected.

**Comment by CAM-Gerlach** [comment]
Fixed by PR #185
