### ISSUE TITLE
Add the same banner used in the website and use the same fonts in its content

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#19]
We need this to have a consistent look and feel between the other pages in the site and our docs.

@dalthviz, please work on this one. For the fonts, please use *Amiri* for headers and *Raleway* for content.

**Comment by ccordoba12** [comment]
Also, the banner should look like this:

    Spyder | Docs                  Home Blog Docs

**Comment by ccordoba12** [comment]
And, links must be red too.

**Comment by CAM-Gerlach** [comment]
I finally figured out why PRs weren't closing the issues they should after merging #21 to master, so we shouldn't have to close these manually anymore. Sorry about that.
