### ISSUE TITLE
Add new pairings between Spyder and spyder-kernels for version 4.1.5 and 4.2.0

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#195]
See https://github.com/spyder-ide/spyder/pull/13679 about it.

@juanis2112, I'll let you know when Anaconda releases new packages for that version, so you can proceed to fix this issue.

**Comment by CAM-Gerlach** [comment]
Since the table lists the Spyder-Kernels version required for each Spyder version, there's no real harm in adding the new one now (its not like its a 4.1.5-only feature). But if for whatever reason we didn't want to merge it until the `defaults` packages go live, we could simply merge the PR then.

**Comment by ccordoba12** [comment]
Sure, no problem with that. However, 4.1.5 is on `defaults` now.

**Comment by CAM-Gerlach** [comment]
@juanis2112 3 month bump. Would you like me to do this instead?
