### ISSUE TITLE
Add FAQ question on switching environments and interpreters based on the new implementation 

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder-docs#197]
## Issue Description
This PR https://github.com/spyder-ide/spyder/pull/13950 improves the way that we display the environments and python interpreters so we should add a FAQ that we can point from preferences to explain people how to do this.

**Comment by CAM-Gerlach** [comment]
Just to clarify, do you mean an FAQ i.e. a whole FAQ page, or an individual FAQ question?
