### ISSUE TITLE
Add additional important information and explanation about new installers

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs#201]
## Issue Description

Currently, the standalone installers section we included as stopgap needs some more additional elements to answer what are likely going to be key user questions about the new installers. We might want to consider adding at least some of the to the FAQ, if you all agree and we indeed start seeing them.

@ccordoba12 @juanis2112 Feel free to edit the below section to add anything else we should mention.

### Where is the relevant portion of the documentation located?

Installation guide, installers section

### What would you suggest it be replaced with?

* [x] All the other install methods mention how to keep Spyder up to date, but this crucial information is missing from the standalone installers, and even I'm not sure what we are recommending. Do users just download the new version and install it on top of it? Use some kind of package manager? Is there, or will there be auto update functionality? Does the UI text in the Spyder update dialog reflect this?

* [x] Similarly, all the other methods describe how to run Spyder after installing. I imagine its simpler and more conventional here (Start menu on Windows, Applications folder on macOS? right?) but it is still worth a mention for clarity

* [x] Describe or link to (e.g. the FAQ question) how to use the standalone version with an existing Anaconda or other install (likely to be very common, esp. at the beginning);

* [x] Explain how users can install their own packages in the environment, or if that is not possible/advisable, what they should do instead (a very common question as you know)

* [x] At least briefly describe the difference between the full and lite installers and why a user might prefer one or the other

* [x] Describe any key bugs/limitations and what to do about them (can the Windows version still not work with Python versions other than its own, etc). 

* [x] Fix installer link display CSS at narrow widths

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

Spyder 4.2.0+

* Are you planning on submitting a Github pull request with a suitable change?

If needed

**Comment by ccordoba12** [comment]
My answers:

> Do users just download the new version and install it on top of it?

Yes, they need to uninstall the previous version and install the new one.

> Is there, or will there be auto update functionality?

No, there isn't and it won't be. I really don't how what you need to do to make that work.

> Does the UI text in the Spyder update dialog reflect this?

Yes, it does. See PR https://github.com/spyder-ide/spyder/pull/14091 for how things look now.

> I imagine its simpler and more conventional here (Start menu on Windows, Applications folder on macOS? right?) but it is still worth a mention for clarity

Yes, that's right. That's the way to start Spyder after installing it with our installers. I also think it's important to mention it in the installation guide.

> Describe or link to (e.g. the FAQ question) how to use the standalone version with an existing Anaconda or other install (likely to be very common, esp. at the beginning);

I agree this is important. Also, adding a new entry to our FAQ sounds like the right thing to do.

> Explain how users can install their own packages in the environment, or if that is not possible/advisable, what they should do instead (a very common question as you know)

They can't install anything in the app, so if they need to use other packages that don't come with it, they need to install Anaconda/Miniconda and connect Spyder to it.

> At least briefly describe the difference between the full and lite installers and why a user might prefer one or the other

Good point. The lite installers don't come with our optional dependencies, that's the only difference. That means people won't be able to view Dataframes and Numpy Arrays. Plotting with Matplotlib should work fine, as long as they have it in their envs.

> Describe any key bugs/limitations and what to do about them (can the Windows version still not work with Python versions other than its own, etc).

I think the main limitation is that the installers need to be connected to Anaconda/Miniconda to work with Scikit-learn, PyTorch, Tensorflow, etc.

A minor limitation is that they don't support code and text snippets (because they don't ship with the `rtree` dependency), but we plan to fix that for Windows in 4.2.1 (still not sure if it's possible to fix it on macOS).

**Comment by CAM-Gerlach** [comment]
Thanks for all your detailed clarifications; that's all very helpful.

> Yes, they need to uninstall the previous version and install the new one.

I see, then we should explicitly mention this then. Manually visiting the site, downloading the new installer, uninstalling the old version and installing the new version seems like a pretty big hassle for compared to just typing `conda update spyder`. @dalthviz @mrclary can the installer at least install on top of the previous installer? As far as I'm aware, I don't recall having to manually uninstall a program before installing a new version at least with a NSIS or DMG installer (as used by the Spyder Windows and macOS builds respectively), it would overwrite the old version automatically.

> No, there isn't and it won't be. I really don't how what you need to do to make autoupdating work.

There's pyupdater, but that only works with pyinstaller, not pyinst. Its possible that the conda-based solution has autoupdate, but that would require switching the packaging stack. I don't really know of a way that works easily with NSIS without writing our own or using a whole separately installed toolkit, and neither on Mac. You could use both platforms' built-in app stores, but that's a whole other can of worms. So yeah looks like there aren't any easy options here, unfortunately.

As for everything else, looks like it should be straightforward to mention, either in this section or link to the existing answers in the FAQ. Would you like me to go ahead with a PR?

**Comment by mrclary** [comment]
@ccordoba12 @CAM-Gerlach ,
* The macOS installer does not require uninstalling previous versions. Once the new version dmg is downloaded, copying the Spyder application into the Applications folder will overwrite the existing version.
* I can look into the code snippet limitation. Just create an issue and assign to me. Previously, `rtree` could not be included in the build, but I can investigate more deeply.
* I know we discussed it before (I don't remember where), but viewing DataFrames and Numpy arrays in the variable explorer editor requires those packages in the standalone application so the Lite version won't be able to do that until we figure out a way for the variable explorer detail editor to access the IPython console environment. Note that this is a limitation even for Spyder launched from an Anaconda environment if that environment doesn't have the requisite packages. This can happen for our heretofore recommended Spyder usage: a dedicated conda environment from which to lauch Spyder (which could be minimal), and separate conda environments for IPython consoles (user's working environments).
* I've already written instructions for my company on how to install Spyder and connect it to external environments. I can contribute to our documentation if you point me to the correct readme file where you want it.

**Comment by ccordoba12** [comment]
> I've already written instructions for my company on how to install Spyder and connect it to external environments. I can contribute to our documentation if you point me to the correct readme file where you want it.

Thanks @mrclary, that would be really helpful.

**Comment by CAM-Gerlach** [comment]
> I know we discussed it before (I don't remember where), but viewing DataFrames and Numpy arrays in the variable explorer editor requires those packages in the standalone application so the Lite version won't be able to do that until we figure out a way for the variable explorer detail editor to access the IPython console environment. 

Yes, and a more serious limitation that specifically affects the installers is support for viewing arbitrary Python objects (e.g. classes from third party packages) in the Variable Explorer provided by packages that aren't in the baseline Spyder environment, which is very common in many scientific workflows. Unlike in Anaconda where you can at least install it in the Spyder environment (though that won't work in cases of conflicts, and doesn't really match the workflow we recommend of keeping the env as minimal as possible), it is simply not possible to view these in the standalone version, as far as I'm aware, which is a pretty big limitation for me (a lot of the utility I get out of the variable explorer is out of introspecting these datatypes.

However, it _should_ be possible to at least recursively serialize the `__dict__` of the object and send that through such that the object explorer can display it usefully, though that might take some work.

> I've already written instructions for my company on how to install Spyder and connect it to external environments. I can contribute to our documentation if you point me to the correct readme file where you want it.

Thanks! We currently have a [FAQ entry](http://docs.spyder-ide.org/current/faq.html#using-spyder) that can be found [here](
https://github.com/spyder-ide/spyder-docs/blob/master/doc/faq.rst) that explains it (its much easier now in 4.2.0 with environment auto-detection), but we'd be happy to see if there's anything we could add or improve from your guide. Is there somewhere we could take a look at it (redacted with any company-specific details as needed), so we can maybe discuss together where might be the best fit for it? Thanks!

**Comment by mrclary** [comment]
@CAM-Gerlach,
I think the short-term solution to the Variable Explorer problem is that users download the full version and we could consider including more packages if there is sufficient demand. There are only two trade-offs:
* The application is much larger. The lite version is ~370MB and the full version is ~600MB (on macOS). The full version would be larger still if additional packages are included.
* The Variable Explorer would be using the "built in" versions of these packages, which could be different from the versions in the external environments. This may or may not present issues for the user if object class definitions between the versions are different.

As for instructions, I cannot direct you to any of our internal websites, but I attached a pdf of the internal page. It does not have any proprietary information. I don't think we'll need most of what is in there, but it should provide a starting point. I can work on transcribing it to the FAQ rst file.

[Spyder Instructions.pdf](https://github.com/spyder-ide/spyder-docs/files/5556652/Spyder.Instructions.pdf)
