### ISSUE TITLE
Add FAQ question on Spyder's license and the impact of the Anaconda EULA change

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs#202]
## Issue Description

We've gotten a number of questions lately (and we've always had a few) about whether Spyder is free for commercial use and distribution, and particularly what the impact of the [Anaconda EULA change](https://www.anaconda.com/blog/sustaining-our-stewardship-of-the-open-source-data-science-community) is on it, now that it seems to have come to the fore. Therefore, it would be good to have a short FAQ question explaining this aspect, based on some of the responses in our Gitter.

Source material to draw from:

> To provide a little more detail, Spyder is community developed and 100% free and open source (there is no paid version or Spyder company, like with most other IDEs, though we do have generous sponsors that help fund our development and specific features). Our source code, standalone installers and most of our distribution methods (pip/PyPI, Linux distros, MacPorts, WinPython, etc) are fully unemcumbered and can be freely redistributed, used and modified by anyone.
> 
> Full-fat Anaconda proper does come with restrictions for big for-profit companies using it on a large scale, but that restriction is only on the package distribution infrastructure (the packaged Anaconda distribution and the `defaults`conda channel); instead, you can simply download the more lightweight [Miniconda](https://docs.conda.io/en/latest/miniconda.html) which is essentially just Anaconda without all the gigabytes of Python package packages installed by default and is 100% open source and free of restrictions, and install whatever you need (including Spyder and any packages you want to work with) from the community maintained `conda-forge` channel, which has a much wider variety of packages and is generally more up to date than the Anaconda `defaults` channel. I actually prefer this approach for the mentioned reasons  and is what I've used for years, despite working as a NASA-funded researcher in academia.

> To clarify this, Spyder now offers standalone installers for Windows and macOS, which don't rely on Anaconda and are 100% free and open source; the download button on our website now points to them instead on the appropriate platforms. And in terms of conda, the situation is actually a good deal more nuanced than this; Anaconda has made statements to the effect that it only applies if you're using it _at scale_ in your large company; if only a few people are actually using it or on a part-time basis, they're not going to go after you. Furthermore, conda itself, Miniconda and Conda-Forge are still 100% free and open source, so its perfectly possible to still use it just as you currently do, with only a few changes to your workflow.

> They can if they install Spyder in its own environment rather than `base`, as has been our official recommendation for years now, and use conda-forge for that env instead of `defaults` (not sure if CF Spyder and Spyder-Kernels will be have compat issue with an all-AD stack beneath it; Spyder itself is pure Python so I'd _think_ not but some packages might  get channel-switched piecemeal so an all-CF Spyder env would naturally be the officially supported solution). Since users don't need to reinstall any of their packages, just Spyder and any optional deps they want to use with it (Numpy, Pandas, Matplotlib, etc), its relatively cheap to simply create a new env for CF Spyder if they happen to haveo one already.

### Where is the relevant portion of the documentation located?

FAQ

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

Yes, Spyder 4.x

* Are you planning on submitting a Github pull request with a suitable change?

Yes

**Comment by ccordoba12** [comment]
This is a very good idea! Thanks @CAM-Gerlach for bringing it up.

**Comment by CAM-Gerlach** [comment]
We'll probably want to update the install guide to, but I can do that as part of implementing #201
