### ISSUE TITLE
Content of the .py file

### ISSUE THREAD

**Issue by Justinas365** [spyder-ide/spyder-docs#216]
## Issue Description
I can not understand how can I see a content in my python file. Since this is the first thing you see on the website, I suppose this feature is available but the explanation how to get there is missing. 
![image](https://user-images.githubusercontent.com/60322278/104074406-f98dca80-5207-11eb-8bb9-d162d3b44b27.png)

### Where is the relevant portion of the documentation located?

I dont know if its located anywhere, if it is I would like for you to pin it. 
![image](https://user-images.githubusercontent.com/60322278/104074530-4bceeb80-5208-11eb-85af-7e955a7eac6b.png)

I would hope to see cells on the left side and perhaps defined functions?

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

* Are you planning on submitting a Github pull request with a suitable change?

* Anything else you'd like to add?

**Comment by Justinas365** [comment]
Please ignore. I spent all evening looking for this and accidently just found.

**Comment by ccordoba12** [comment]
Glad you found the solution @Justinas365.
