### ISSUE TITLE
FAQs and other dropdowns not uncollapsed when they contain highlighted search terms

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder-docs#250]
# Issue Report

## Issue Description

We need to add code for the search button to search for text inside the FAQ answers. As the answers are collapsed by default the page doesn't show results In the answers.

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

* Are you planning on submitting a Github pull request with a suitable change?

* Anything else you'd like to add?

**Comment by CAM-Gerlach** [comment]
While search finds text inside FAQ answers just fine, the issue that it appears the above is referring to is that question(s) that contain highlighted/matched text are not uncollapsed. I can solve that in a PR with some custom JavaScript.
