### ISSUE TITLE
Decide on and implement a common heading and body font size between the docs and the blog

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs#26]
## Issue Description

To summarize, the initial idea behind of #19 was to harmonize the banner and the fonts used between the docs and the website (really, with the blog rather than the mainpage with respect to the latter as it stands currently, due to the sans font for the headings). Following some requested changes, the font sizes for the doc headings and body diverged from that used on the blog. However, as discussed in #21 and elsewhere, as the current font sizes on the blog is on the larger end of the acceptable range, while the docs could still tolerate a bump, and its best to keep them consistent, it would probably be a good idea to re harmonize them, so we can discuss that here.

### Where is the relevant portion of the documentation located?

The CSS layout file.

### What would you suggest it be replaced with?

Perhaps the best solution is to bump the doc body font up one more size to 16.8px, and bump the blog down one to that (from 18px) as well. It should be a good compromise between the two, and will also match the sidebar main font size as well. Accordingly, the top/main and sub heads of the blog could also be brought down to 37px and 27.7px from 48px and 39.6px respectively to match as well, as they are quite big as is, although both (the docs and the blog) and the could be brought to a size a little bigger than the current docs if the latter is a bit too small for the blog.

@ccordoba12 and @dalthviz , your thoughts?

**Comment by CAM-Gerlach** [comment]
@ccordoba12 ? @dalthviz ?

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Any updates, now that #44 is up and the I.P.R. is within reach? It'd be nice to have this finalized by the official release, if possible...

**Comment by CAM-Gerlach** [comment]
@ccordoba12 @dalthviz At this point, I just went ahead with a PR to harmonize the main body and sidebar font size to 16px, as well as a few other minor tweaks along those lines. It should be applied here regardless to make at least things here a little more optimal and internally consistent, although it would be nice to have the blog font harmonized (and a little smaller) before my posts start going up there. I'll open an issue over there.

**Comment by ccordoba12** [comment]
Closing this one because we decided against using the same style in both places.
