### ISSUE TITLE
Remove our pythonhosted.org and RTD docs

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#28]
Once our new docs are ready for the world, we need to remove the old copy in pythonhosted.org

* [x] Read the Docs docs
* [ ] PythonHosted.org docs

**Comment by CAM-Gerlach** [comment]
Thanks. One thing to keep in mind is that the PyHosted version will still be the one linked to from the first and most prominent item in the Spyder help menu in any Spyder version before 3.3, and (IIRC the default mapping) are even opened by default with the <kbd>F1</kbd> keyboard shortcut. Therefore, it would seem prudent to wait at least until the release of 3.3 and its incorporation into the current official Anaconda version, and/or implement a redirect (manual or automatic) to our new docs from that page, if that's possible.

**Comment by ccordoba12** [comment]
Very good points, thanks! Then, we need to leave those docs live and redirect the `F1` shortcut to our new docs since Spyder 3.3.

Could you open an issue about this in the Spyder repo, so we don't forget to do it? Thanks!

**Comment by CAM-Gerlach** [comment]
Way ahead of you, boss :) I've had PR #7007 open to update all the PyHosted links and close #5986 for a while now, ready to merge as soon as we close the I.P.R. milestone (basically, #14 , #13 and #26 ).

**Comment by CAM-Gerlach** [comment]
Perhaps we can pencil in a nominal removal date of December 31, 2018, assuming the last I.P.R work item is complete (making the layout width-adaptive so the site isn't broken on many screen setups) reasonably soon so we can proceed with #39 .

**Comment by ccordoba12** [comment]
> Perhaps we can pencil in a nominal removal date of December 31, 2018

I was thinking on doing it sooner (perhaps a month or two?). I know this would break old releases, but while our pythonhosted docs are up, they'll be picked up and shown first by Google.

> making the layout width-adaptive so the site isn't broken on many screen setups

Yes, I'll tell @dalthviz to work on that one after we release 3.3.1.

**Comment by ccordoba12** [comment]
> We should at least wait until a month or so after 3.3.1 is included in an official release of the anaconda metapackage, in WinPython and (preferably) most of our Linux downstreams, to give the bulk of our users a chance to update from 3.2.8.

Right, good idea. Unfortunately, waiting for Linux distros to update to this version could delay us for 6 months to a year (even more). So we have to proceed when Anaconda and WinPython are ready (Linux distros are a lost case, really).

> Are you sure?

Ok, perhaps after #39.

**Comment by CAM-Gerlach** [comment]
> Unfortunately, waiting for Linux distros to update to this version could delay us for 6 months to a year (even more). 

Yeah, I figured Debian we could ignore since they are still on 3.2.6 on unstable; the other ones are all on 3.2.8 (with a few already on 3.3.0), and I meant on their most bleeding edge/unstable repo (i.e. the ones linked in our install guide).

**Comment by CAM-Gerlach** [comment]
> Ok, perhaps after #39.

Yeah, we'll see after that. Of course, even if so we'll still want to remove them within a reasonable timeframe. #39 is definitely a blocker on doing so, in addition to the 3.3.1 availability criterion.

**Comment by CAM-Gerlach** [comment]
Thanks @ccordoba12 !
