### ISSUE TITLE
Spyder 5 FAQs page is out of date for Spyder-Kernels versions, and "installing and updating Spyder"

### ISSUE THREAD

**Issue by richlysakowski** [spyder-ide/spyder-docs#308]
# Issue Report

## Two issues I found tonight...

The Spyder FAQs page is out of date for Spyder-kernels versions... https://docs.spyder-ide.org/current/faq.html

I am running Spyder 5.1.5 and it complains about the correct version of `spyder-kernels` not being installed.   I have 1.10.2 installed and Spyder 5.1.5 requires 2.2.1. 

![image](https://user-images.githubusercontent.com/9345711/153337830-0f12fe07-2423-4e23-bc13-5f7cecd55894.png)

### Where is the relevant portion of the documentation located?

See the following link: 

    [https://docs.spyder-ide.org/current/faq#troubleshooting-starting-kernel](url)

### What would you suggest it be replaced with?

Please update the table in the documentation page above, and more importantly, please update the Spyder 5.x package installers to install the correct version of spyder-kernels.  

### the "installing and updating Spyder" section is also out of date...

Also, the code ```conda install spyder=4``` in the following FAQs page section is also out of date for Spyder 5.1+

See the following link: 

![image](https://user-images.githubusercontent.com/9345711/153339240-30891c68-76cc-4871-9656-04a0b24748e8.png)

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

Yes

**Comment by CAM-Gerlach** [comment]
Thanks! I opened #309 to resolve this
