### ISSUE TITLE
conda create command installs Spyder version 4

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-docs#313]
# Issue Report

## Issue Description

The installation guide has a `conda create` command which specifies that Spyder version 4 be installed.

### Where is the relevant portion of the documentation located?

The section "New Conda environment" in the installation guide.

### What would you suggest it be replaced with?

I don't know why the Spyder version number was specified, but it should be updated with every major release or removed. The latter option seems the simplest.

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

It seems only present in the docs for Spyder 5.

* Are you planning on submitting a Github pull request with a suitable change?

Yes.

* Anything else you'd like to add?

**Comment by CAM-Gerlach** [comment]
Good catch, thanks!
