### ISSUE TITLE
Include creating and activating environment details in the current docs contributing guide 

### ISSUE THREAD

**Issue by hyounes4560** [spyder-ide/spyder-docs#318]
# Issue Report

## Issue Description
There is a minor issue in the current "Contributing to the Spyder Documentation" file that may waste contributors' time while attempting to build the docs locally. Currently, the docs' contributing guide is missing any instructions on "Creating an environment" and jumping directly to installing dependencies. It only mentions that "dependencies should be installed in an active Python environment". This information may sound trivial for tech-savvy contributors; however, documentation contributions come from tech and non-tech community members.   

### Where is the relevant portion of the documentation located?

"CONTRIBUTING.md" file 

### What would you suggest it be replaced with?

Simply adding a few lines to create and activate an environment. 

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

    * [X] N/A
    * [ ] Spyder 5 (``master``)
    * [ ] Spyder 4 (``4.x``)
    * [ ] Spyder 3 (``3.x``, frozen)

* Are you planning on submitting a Github pull request with a suitable change?

    * [X] Yes
    * [ ] No
    * [ ] Maybe so

**Comment by CAM-Gerlach** [comment]
Hey, thanks for the report! I'd thought I'd ported over the updated, standardized version of the Contributing Guide we now use on our website, QtPy, Docrepr and elsewhere which includes this information and much more that is helpful for walking newer and less tech-savvy contributors through every step of the contributing process, but it seems I never had. I've pulled over the updated sections and made a number of other improvements as well in PR #319 . I'd really appreciate any further suggestions or feedback you might have over there, thanks!

**Comment by hyounes4560** [comment]
@CAM-Gerlach should I mark this as a Duplicate? Thanks

**Comment by CAM-Gerlach** [comment]
Oh no, not at all—we didn't already have an issue open about updating the contributing guide, so its helpful that you did. I linked PR #319 as resolving this issue, so when that is merged, the issue will be closed automatically. Thanks!
