### ISSUE TITLE
Add warning not to import untrusted data in Variable Explorer

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-docs#328]
# Issue Report

## Issue Description

Importing untrusted data in the variable explorer is unsafe because it uses pickle which executes arbitrary code. Users should be warned against this.

### Where is the relevant portion of the documentation located?

Second line of https://github.com/spyder-ide/spyder-docs/blob/master/doc/panes/variableexplorer.rst#toolbar-buttons

### What would you suggest it be replaced with?

Add a warning.

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

    * [x] N/A
    * [ ] Spyder 5 (``master``)
    * [ ] Spyder 4 (``4.x``)
    * [ ] Spyder 3 (``3.x``, frozen)

* Are you planning on submitting a Github pull request with a suitable change?

    * [ ] Yes
    * [x] No
    * [ ] Maybe so

**Comment by CAM-Gerlach** [comment]
Thanks for documenting this; I've opened #330 to add it.
