### ISSUE TITLE
no theme named 'pandas_sphinx_theme' found (missing theme.conf?)

### ISSUE THREAD

**Issue by katxeus** [spyder-ide/spyder-docs#337]
Would please like to get some clarity on how or from where I can install the pandas_sphinx_theme specified in the conf.py. I tried
 `pip install pandas-sphinx-theme `
But all i could get was the error 
`no theme named 'pandas_sphinx_theme' found (missing theme.conf?)`

**Comment by CAM-Gerlach** [comment]
Hey, did you follow the [instructions in the Contributing Guide](https://github.com/spyder-ide/spyder-docs/blob/master/CONTRIBUTING.md#setting-up-a-development-environment)? Following that will install all the required dependencies, including our heavily modified fork of the theme.

**Comment by katxeus** [comment]
> 

Great thanks, I had missed it entirely.

**Comment by CAM-Gerlach** [comment]
Great, seems like this is resolved then :+1:
