### ISSUE TITLE
FAQ section - instructions for selecting conda environment

### ISSUE THREAD

**Issue by mik-ohdsi** [spyder-ide/spyder-docs#340]
# Issue Report
FAQ section - selecting conda environment, Win 11, miniconda 3.10

## Issue Description
I had a hard time figuring out that after selecting my conda from the dropdown list, the console did not work as there were no spyder-kernels although I had been going through the steps before. It took me a while to realize that the environment read "base". In the conda terminal I then listed the environments and found the path to the spyder-env in Users\<myuser>\.conda\envs\spyder-env . Pointing it there "manually" finally did the trick.

### Where is the relevant portion of the documentation located?
In the section for using [miniconda with Spyder](https://docs.spyder-ide.org/5/faq.html#using-packages-installer), there is a paragraph about finally selecting the environment: `"...use the dropdown below to select your preferred environment. If it is not listed, use the text box or the Select file button to enter the path to the Python interpreter you want to use."`

### What would you suggest it be replaced with?
Put in a word of warning that depending on how the install has been done (all users, individual user etc), the dropdown option might not  be the environment that has been created in the previous step.
Maybe add a hint that `conda env list` would show the active environment and its location.

### Other information
* Is the problem specific to documentation for a particular version of Spyder?

    * [X] N/A
    * [ ] Spyder 5 (``master``)
    * [ ] Spyder 4 (``4.x``)
    * [ ] Spyder 3 (``3.x``, frozen)

* Are you planning on submitting a Github pull request with a suitable change?

    * [ ] Yes
    * [X] No
    * [ ] Maybe so

**Comment by CAM-Gerlach** [comment]
Hey, thanks for taking the time to file a detailed report.  I first want to be sure I understand the specific difficulty you had here, so we can best update the docs (and perhaps Spyder itself) to address it, but one thing I noticed we can definitely add is how to get the path to the Python executable in the currently activated environment, i.e. with `python -c "import sys; print(sys.executable)"`.

A few additional questions to clarify some points:

> It took me a while to realize that the environment read "base".

Assuming you mean that the environment in the _Spyder statusbar_ was indicated as `base`, I'm guessing you just selected the path to your (all users/global, I'm assuming) Anaconda install, as opposed to the actual environment you created.

Did you not see the environment you created in the dropdown? If not, maybe Spyder can also search the `~/.conda/envs/` directory for local user environments in case of a global install, which I'm guessing is what happened here...

@dalthviz , any insight or thoughts on that?

> Put in a word of warning that depending on how the install has been done (all users, individual user etc), the dropdown option might not be the environment that has been created in the previous step.

In the passage you quoted, we already warn users that "If it is not listed, use the text box or the Select file button to enter the path to the Python interpreter you want to use", i.e. if the environment you want (e.g. `spyder-env` in your particular case) isn't listed there, then you have to navigate to and select it manually. Could you explain a little more about what confused you about this?

Also can you confirm if you using a global ("for all users") Miniconda install (I'm guessing that's what happened, but it is never stated explicitly)?

> Maybe add a hint that `conda env list` would show the active environment and its location.

In fact, running `python -c "import sys; print(sys.executable)"` will print the direct path to the Python interpreter in the currently activate environment, which can be pasted directly into that dialog (as opposed to `conda info --envs`, or the legacy `conda env list` you suggest, which just lists the base prefix for all environments, including the activated one). It also works regardless of whether you're using conda, venv/virtualenv, or any other Python distribution/environment manager.

Thanks!

**Comment by mik-ohdsi** [comment]
Hi @CAM-Gerlach , thanks for answering. 
I guess the confusion came from the fact that in the dropdown was one entry which I happily selected, but that was only the "base" env. The spyder-env did not show up as an option and it just took me quite a while to realize that. Only after I read a couple of pages about environments mentioning the "base" environment I noticed that the bottom line actually showed that I selected the base env. I then followed the instruction to locate the spyder-env manually.
cheers - mik

**Comment by CAM-Gerlach** [comment]
Hi @mik-ohdsi , thanks for the clarification and sorry for the delay responding—I've been busy with some other tasks.

We'll definitely update the docs to improve those FAQ questions and clarify how to get the environment path, as you suggest. However, we also want to try to diagnose and fix the issue with Spyder not detecting your environments, as it certainly should be able to do so automatically. I tested it on Linux on an all-users install, and it indeed worked as expected, and I confirmed with @ccordoba12 that Spyder uses the output of `conda env list` to get the list of Conda environments, which you confirmed _was_ showing your environment for you.

Therefore, we're not totally sure why it didn't show up in the list; the likely possibilities seem to be that it's a Windows-specific issue, or there's something specific with the characters in username, or something else in your environment that's causing it. To help us try to solve this issue, could you provide the following previously requested information, inside of code blocks like this:


~~~md

```console

<COMMAND AND OUTPUT HERE>

```

~~~

* The version information under `Spyder` -> `Help` -> `About` -> `Copy version info`
* `conda info` in your Anaconda prompt
* `conda info --envs` in your Anaconda prompt
* `conda env list --json` in your Anaconda prompt
* A screenshot of Spyder's `Python interpreter` preferences with the dropdown open

If you wouldn't mind retaining your user name there, we need to check in case there are any characters there Spyder might not be handling correctly. Thanks!

**Comment by CAM-Gerlach** [comment]
FYI @mik-ohdsi , I've also opened a PR #346 that overhauls both these FAQ questions to specifically address these concerns, as well as overall being much more clear and helpful, easier to follow and less confusing.

**Comment by mik-ohdsi** [comment]
1)
* Spyder version: 5.4.1  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10
2)
     active environment : base
    active env location : C:\ProgramData\miniconda3
            shell level : 1
       user config file : C:\Users\MichaelKallfelz\.condarc
 populated config files : C:\Users\MichaelKallfelz\.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\ProgramData\miniconda3  (read only)
      conda av data dir : C:\ProgramData\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\miniconda3\pkgs
                          C:\Users\MichaelKallfelz\.conda\pkgs
                          C:\Users\MichaelKallfelz\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\MichaelKallfelz\.conda\envs
                          C:\ProgramData\miniconda3\envs
                          C:\Users\MichaelKallfelz\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.10.8 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False
3)
# conda environments:
#
base                  *  C:\ProgramData\miniconda3
spyder-env               C:\Users\MichaelKallfelz\.conda\envs\spyder-env
4)
{
  "envs": [
    "C:\\ProgramData\\miniconda3",
    "C:\\Users\\MichaelKallfelz\\.conda\\envs\\spyder-env"
  ]
}
5)
![grafik](https://user-images.githubusercontent.com/60365423/218806157-0ac81a25-3cb8-4c75-97e8-130c1bef09f3.png)

**Comment by CAM-Gerlach** [comment]
Thanks for the detailed and helpful information! We'll take a closer look.

You're also welcome to provide any feedback on PR #346 , which overhauls the FAQ questions related to this.
