### ISSUE TITLE
Document cell grouping

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#40]
See spyder-ide/spyder#7107

**Comment by juanis2112** [comment]
Will add this as a feature of the editor

**Comment by CAM-Gerlach** [comment]
As the linked issue describes, this is not a feature of the Editor, but rather of the Outline pane. I believe it would make sense to cover it in that pane.

**Comment by ccordoba12** [comment]
+1 to @CAM-Gerlach's suggestion.

**Comment by CAM-Gerlach** [comment]
Closing manually since auto-closed got confused due to "issue" separating "fix" and the number.
