### ISSUE TITLE
Update installation instructions to account for new spyder-kernels dependency

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs#55]
## Issue Description

Per spyder-ide/spyder#7337 (and ultimately due to  spyder-ide/spyder#7306 ), installation instructions will need to be updated to clarify the need for an additional dependency, ``spyder-kernels``, which will in turn need to be for the correct version of spyder (3.x or 4/master).

### Where is the relevant portion of the documentation located?

Installation instructions docs, specifically installing from source and setting up a development environment sections.

### What would you suggest it be replaced with?

Reminding the user to install the dependency, and the different procedure for ``master`` vs. ``3.x``.

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

Spyder 3.3 onward, and particularly for work on ``master``.

**Comment by ccordoba12** [comment]
This is really important because without the right version of spyder-kernels, or simply without it, Spyder won't launch.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I can try to do it later tonight, since it should be quick presumably. I was just at the eye doctor so I can't read very well right now but it should be back to normal by the time I get home from dinner with my dad in a few minutes.
