### ISSUE TITLE
Make content width adaptive to window size instead of cutting off text

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs#63]
## Issue Description

Currently, our docs content (and sidebar) is a fixed width, which results in hard cutting off of the text in many scenarios, and even worse, scrolling past the edge doesn't render the missing text. This forces us to either exclude large classes of user setups/use cases from being able to view the docs properly, or use an unreasonably narrow content width.

![image](https://user-images.githubusercontent.com/17051931/42246426-7fe58d6e-7eea-11e8-93da-b3fd9c753ffd.png)

The solution is to make the width of the docs content (and perhaps the sidebar, to a lesser extent) adaptive; i.e. starting at 1200 px max total width and then reducing the width and soft-wrapping the text if the window is smaller than that; also, we can pin the sidebar to one side to make the margins more even. Basically, something like this [Github books output](http://www.theia-ide.org/doc/authoring_extensions) mentioned by @ccordoba12 .

Hopefully its possible to do in CSS but if not, then some simple JS perhaps. I'm guessing @dalthviz would be the one to do this?

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one. Take a look at how Github books work, as @CAM-Gerlach suggested.

Also, this probably requires you to add some additional Javascript to the output generated by Sphinx. I mean, I don't think this could be done with CSS alone (but I could be wrong).

**Comment by CAM-Gerlach** [comment]
This is currently more serious than initially though, since right now thanks to the increases in the sidebar and total content width, the docs are cut off and essentially unreadable if the window width is less than 1100 px (on a portrait-format display common in software development, when split to one half of a 1080p monitor, on older monitors, on mobile devices, etc,) with **no** scrollbar and thus no ability to even scroll to see the missing portions on either Chrome or Firefox; the above is just how it looks when rendered locally but on our actual site there is no scrollbar at all. 

This is a major issue from a usability perspective, completely breaking many likely desired use-cases. A temporary fix to at least make it usable in most of these scenarios would be reducing the total width back to 900 or 960 px as I had it (for exactly this reason), but something like what @ccordoba12 suggested with Git Books is a far better permanent solution all around.

**Comment by CAM-Gerlach** [comment]
Fixed by PR #127
