### ISSUE TITLE
Jupyter Core Paths error

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder-docs#82]
## Issue Description
In ipythonconsole.rst

```
import jupyter_core
jupyter_core.paths.jupyter_runtime_dir()
```
On my install (anaconda latest) gives
```
AttributeError: module 'jupyter_core' has no attribute 'paths'
```
Should be 
```
import jupyter_core.paths
jupyter_core.paths.jupyter_runtime_dir()
```
or even from terminal
```
jupyter --runtime-dir
```

### Where is the relevant portion of the documentation located?

/doc/ipythonconsole.rst line 51

### What would you suggest it be replaced with?

```
import jupyter_core.paths
jupyter_core.paths.jupyter_runtime_dir()
```
or from terminal
```
jupyter --runtime-dir
```

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

No

* Are you planning on submitting a Github pull request with a suitable change?

I can

* Anything else you'd like to add?

No I'm good

**Comment by ccordoba12** [comment]
> jupyter --runtime-dir

This one is better. @CAM-Gerlach, what do you think about changing our docs to this instead?

**Comment by CAM-Gerlach** [comment]
Sorry I missed this somehow. Thanks for the catch, @bcolsen 

> This one is better.

Very much agreed; way less complex and involved, and not only that but it obviates some of the extra verbiage and complexity added in #79 that I wasn't a huge fan of, jeje.

Already done, opening a PR momentarily.
