### ISSUE TITLE
More dependencies for Spyder 4

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#87]
in spyder-ide/spyder#8004, I'm declaring two new dependencies: `pexpect` and `paramiko`. Both are needed to have remote kernel connections through SSH.

@CAM-Gerlach, please update our docs to reflect that.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I assume ``qdarkstyle`` should be added as well?

**Comment by ccordoba12** [comment]
Yes, that's correct. You can leave this open until we define all our deps for beta2 (although I'm not expecting more, but you never know :-)

**Comment by CAM-Gerlach** [comment]
Okay, thanks. Will do.

**Comment by juanis2112** [comment]
Removing dependencies for new docs
