### ISSUE TITLE
Describe how to launch Spyder after installing via various methods

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs#89]
## Issue Description

As noticed by multiple users on our Gitter, our documentation currently doesn't include any mention of how to actually launch Spyder after install via various means (``pip``, ``conda``, etc). Therefore, we should mention such in our install docs.

### Where is the relevant portion of the documentation located?

Installation doc

**Comment by ccordoba12** [comment]
We have to mention that on Linux and macOS people can't launch Spyder through traditional means (i.e. the main dekstop menu or Spotlight, respectively). They only can use Navigator or a terminal.

**Comment by juanis2112** [comment]
@CAM-Gerlach  please include this in our installation guides

**Comment by CAM-Gerlach** [comment]
Will do, thanks.
