### ISSUE TITLE
Update maintainer in AUTHORS.txt

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-docs#98]
@ccordoba12 [AUTHORS.txt](https://github.com/spyder-ide/spyder-docs/blob/master/AUTHORS.txt) is now out of date.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 6 months bump

**Comment by CAM-Gerlach** [comment]
@ccordoba12 @juanis2112 Pretty please?

**Comment by ccordoba12** [comment]
Please submit a PR with this fix. I don't understand why you can't help us with that if it's so important to you.

**Comment by CAM-Gerlach** [comment]
Because as you _de facto_ removed me as maintainer, unlike yourself it is inherently no longer within my responsibility, authority nor knowledge to update `AUTHORS.txt` to accurately reflect the whomever has replaced me in the job (@juanis2112 ?). Furthermore as a practical matter, if it's @juanis2112 I either do not know or at do not have explicit permission to share her full name and email, so either you or her would need to be involved to do it anyway.
