### ISSUE TITLE
Create tutorial for making a brand new spyder plugin

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder-docs#99]
## Issue Description
Create a new tutorial for contributors that want to create a new spyder plugin

**Comment by juanis2112** [comment]
Closing this issue because it is not useful with new API

**Comment by CAM-Gerlach** [comment]
We should still create a tutorial, just for the new API rather than the now-current one, to make it much easier to create a Spyder plugin for anyone who already doesn't happen to be familiar with the API (which even most of us aren't).
